language: scala
sudo: false
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
script:
- sbt ++$TRAVIS_SCALA_VERSION test:scalafmt test
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
scala:
- 2.11.11
matrix:
  include:
  - scala: 2.12.2
jdk: oraclejdk8